version: '3'
services:
  nginx:
    image: ${REGISTRY_ADDRESS}-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - php-fpm
  php-fpm:
    image: ${REGISTRY_ADDRESS}-php-fpm:${IMAGE_TAG}
    networks:
      - main
    depends_on:
      - mysql
  php-cli:
    image: ${REGISTRY_ADDRESS}-php-cli:${IMAGE_TAG}
    networks:
      - main
    depends_on:
      - mysql
  mysql:
    image: ${REGISTRY_ADDRESS}-mysql:${IMAGE_TAG}
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - main
networks:
  main:
    driver: bridge
